name: Elixir CI

on:
  push:


jobs:
  build:
    name: compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      id: setup-elixir
      with:
        otp-version: '26.2.3'
        elixir-version: '1.18.0'
        install-hex: true
        install-rebar: true

    - name: Restore Hex and Mix cache
      uses: actions/cache@v4
      id: mix-cache
      with:
        path: |
          ~/.mix
          ~/.hex
        key: ${{ runner.os }}-mix-26.2.3-1.18.0-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-26.2.3-1.18.0-

    - name: Install dependencies
      run: mix deps.get

    - name: Compile with warnings as errors
      run: mix compile --warnings-as-errors


    - name: Upload compiled artifacts and deps
      uses: actions/upload-artifact@v4
      with:
        name: elixir-build-artifacts
        path: |
          _build/
          deps/
          mix.lock
        retention-days: 1


  test:
      name: Run Tests with Database
      runs-on: ubuntu-latest
      needs: [build]

      services:
        postgres:
          image: postgres:15
          env:
            POSTGRES_USER: apex
            POSTGRES_PASSWORD: apex
            POSTGRES_DB: apex_erp_test
          ports:
            - 5432:5432
          options: >-
            --health-cmd "pg_isready -U apex -d apex_erp_test"
            --health-interval 5s
            --health-timeout 5s
            --health-retries 5

      steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download compiled artifacts and deps
        uses: actions/download-artifact@v4
        with:
          name: elixir-build-artifacts
          path: .

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        id: setup-elixir 
        with:
          otp-version: '26.2.3'
          elixir-version: '1.18.0'
          install-hex: true 
          install-rebar: true

      - name: Restore Hex and Mix cache (for test job)
        uses: actions/cache@v4
        id: mix-cache-test
        with:
          path: |
            ~/.mix
            ~/.hex
          key: ${{ runner.os }}-mix-26.2.3-1.18.0-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-26.2.3-1.18.0-

      - name: Install dependencies (again in test job to ensure correct setup)

        run: mix deps.get

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready on localhost:5432 for user apex..."
          until pg_isready -h localhost -p 5432 -U apex -d apex_erp_test; do
            echo "Still waiting..."
            sleep 2
          done
          echo "PostgreSQL is ready!"
        env:
          PGPASSWORD: apex

      - name: Drop, Create, and Migrate Test Database
        run: |
          mix ecto.drop
          mix ecto.create
          mix ecto.migrate
        env:
          DATABASE_URL: "ecto://apex:apex@localhost/apex_erp_test"
          MIX_ENV: test

      - name: Run tests
        run: mix test
        env:
          MIX_ENV: test
          DATABASE_URL: "ecto://apex:apex@localhost/apex_erp_test"